
-- 忽略外键与 RLS 直接在 DB 层面强制覆盖对应数据
UPDATE public.campuses 
SET admission_results = '["https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_14.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_12.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_11.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_10.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_09.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_08.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_07.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_06.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_05.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_04.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_03.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_02.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2025_01.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2024_07.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2024_06.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2024_05.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2024_04.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2024_03.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2024_02.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/milan/2024_01.png"]'::jsonb
WHERE slug = 'milan';

UPDATE public.campuses 
SET admission_results = '["https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2025_13.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2025_06.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2025_05.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2025_04.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2025_03.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2025_02.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2025_01.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2024_04.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2024_03.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2024_02.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2024_01.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2023_04.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2023_03.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2023_02.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2023_01.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2022_08.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2022_04.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2022_03.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2022_02.png","https://ypfnwbkjojocdjwvanfe.supabase.co/storage/v1/object/public/images/admission-results/florence/2022_01.png"]'::jsonb
WHERE slug = 'florence';
