-- 1. 向 site_settings 表插入/更新所有首页和导航栏的配置项
INSERT INTO public.site_settings (key, value)
VALUES 
    ('nav_home', '首页'),
    ('nav_academies', '美院专业介绍'),
    ('nav_courses', '课程体系'),
    ('nav_faculty', '专业师资'),
    ('nav_cases', '优秀案例'),
    ('nav_about', '关于我们'),
    ('nav_cta', '立即咨询'),
    ('hero_tag', 'Rinascimento e Futuro'),
    ('hero_title_1', '在文艺复兴的摇篮'),
    ('hero_title_2', '开启你的艺术未来'),
    ('hero_subtitle', '专业意大利艺术留学预科教育，连接佛罗伦萨与世界，为每一位追求纯粹艺术的灵魂开启通往顶尖美院之门。'),
    ('hero_cta_text', '立即了解计划'),
    ('hero_bg_url', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBX2o-3Zwknhnc3FI0d_ODRa2ZIYBx3Xao1MRakoBthiEGxcmqWzko7lNm_9ZivJ_Y6K11gREKYqWysm-52RRxDrNMO3ALel2uOrOeumeMQV4wIg2hF-dN7y08xHSv6JnimLa028Gp0e9KwFliD6VZzeCJx8NpOQ5ggHmEYf_ZDJwBVI_1lwBFOj29L_OBwwzF9CCZJkjPD4ig-oDmYXWyoTJYhuUEPuMKFrZz0O0VYIlNlVXInfYuK5ycMXRfkiXBxdSHG9ZqxSvCp'),
    ('home_campuses_tag', 'Campus e Galleria'),
    ('home_campuses_title', '校区与学生<br />作品展示'),
    ('home_curriculum_tag', 'Struttura Didattica'),
    ('home_curriculum_title', '课程体系重塑'),
    ('home_faculty_tag', 'Docenti Internazionali'),
    ('home_faculty_title', '连接中意艺术桥梁<br />国际艺术导师'),
    ('home_faculty_cta', '查看全部导师')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 2. 创建 home_curriculums 表管理复杂的首页课程板块
CREATE TABLE IF NOT EXISTS public.home_curriculums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sort_order INTEGER NOT NULL DEFAULT 0,
    number_label TEXT NOT NULL,
    title_cn TEXT NOT NULL,
    icon_name TEXT NOT NULL DEFAULT 'Palette',
    objective TEXT NOT NULL,
    duration TEXT NOT NULL,
    methodology TEXT NOT NULL,
    core_points JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 设置 RLS 允许公开读取
ALTER TABLE public.home_curriculums ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access to home_curriculums" ON public.home_curriculums;
CREATE POLICY "Allow public read access to home_curriculums" ON public.home_curriculums FOR SELECT USING (true);

-- 插入默认的两大课程数据
INSERT INTO public.home_curriculums (sort_order, number_label, title_cn, icon_name, objective, duration, methodology, core_points)
VALUES 
(1, '01', '艺术预科 (Corso Propedeutico)', 'Palette', '零基础或基础薄弱学生，建立完整的西方艺术思维体系与基础技能。', '6-8 个月', '工坊式教学', '["艺术史与现当代艺术理论", "基础造型与色彩实验", "创意思维与材料探索", "意大利语艺术词汇强化"]'::jsonb),
(2, '02', '升学辅导 (Preparazione all''Ammissione)', 'GraduationCap', '针对目标院校要求，完成高质量作品集创作及入学面试准备。', '3-6 个月', '1对1导师制', '["个人艺术项目深度开发", "作品集排版与视觉呈现", "教授模拟面试与作品答辩", "院校申请与注册全程指导"]'::jsonb)
ON CONFLICT DO NOTHING;
