-- ============================================================
-- 课程体系页面可编辑化 — SQL 迁移脚本
-- ============================================================

-- 1. course_overviews 表 (用于 /courses 概览页)
CREATE TABLE IF NOT EXISTS course_overviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    highlights JSONB DEFAULT '[]',
    image_url TEXT,
    link TEXT NOT NULL,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. coaching_levels 表 (用于 /courses/coaching 课程阶梯)
CREATE TABLE IF NOT EXISTS coaching_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_num TEXT NOT NULL,
    title TEXT NOT NULL,
    features JSONB DEFAULT '[]',
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. coaching_services 表 (用于 /courses/coaching 增益服务)
CREATE TABLE IF NOT EXISTS coaching_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon_name TEXT,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. 启用 RLS 并允许匿名读取
ALTER TABLE course_overviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许匿名读取课程概览" ON course_overviews FOR SELECT USING (true);

ALTER TABLE coaching_levels ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许匿名读取辅导阶梯" ON coaching_levels FOR SELECT USING (true);

ALTER TABLE coaching_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许匿名读取增益服务" ON coaching_services FOR SELECT USING (true);

-- 5. 插入种子数据
INSERT INTO course_overviews (title, description, highlights, image_url, link, sort_order) VALUES
('艺术预科基础课程', '专为零基础或基础薄弱的学生设计，系统建立西方艺术思维体系与基础技能。涵盖素描、色彩、艺术史及创意思维训练。', '["6-8个月密集训练", "意大利语艺术词汇强化", "工坊式沉浸教学"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBX2o-3Zwknhnc3FI0d_ODRa2ZIYBx3Xao1MRakoBthiEGxcmqWzko7lNm_9ZivJ_Y6K11gREKYqWysm-52RRxDrNMO3ALel2uOrOeumeMQV4wIg2hF-dN7y08xHSv6JnimLa028Gp0e9KwFliD6VZzeCJx8NpOQ5ggHmEYf_ZDJwBVI_1lwBFOj29L_OBwwzF9CCZJkjPD4ig-oDmYXWyoTJYhuUEPuMKFrZz0O0VYIlNlVXInfYuK5ycMXRfkiXBxdSHG9ZqxSvCp', '/courses/foundation', 1),
('转学/升学/毕业辅导', '针对目标院校的具体要求，由资深导师一对一指导，完成高质量的作品集创作，并进行入学面试的全面准备。', '["3-6个月个性化指导", "个人艺术项目深度开发", "教授模拟面试与答辩"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBcrlHoaQVhuR1sZUrMNYRzToTbwxbMts1qxtma1i_g9q85WNXgSZdDvvMeU7dY1_Iew52-wB_xXCmPH_FI5F5fskSPuTUq7ccHFOoa73SkMz68fU2c3y7pt0nKyjiN92YqOJcs1FhcfXEsPUf-48gyBH4g9GF0iQZqdNHhlKaObZkMuLpo6DXF23JcPCMO1N8qlHfnFlVFTnJT05M3y0K7NEjDrmu2d7mS0LWmNRMwN2Zm-IUzW6p5f0EEBrmevas2E8-DbmMO7MA4', '/courses/coaching', 2);

INSERT INTO coaching_levels (level_num, title, features, sort_order) VALUES
('01', '基础辅导课程', '["20个精品课时", "1对1 深度指导", "锁定1所目标美院", "1场全仿真模拟面试"]'::jsonb, 1),
('02', '标准进阶课程', '["40个精品课时", "1对1 专业陪跑", "针对1所核心美院", "2场全仿真模拟面试", "包含排版与画册制作指导"]'::jsonb, 2),
('03', '全能进阶课程', '["60个精品课时", "1对1 资深导师", "冲刺3所目标美院", "2场高强度模拟面试", "文案润色 / 外教语言指导"]'::jsonb, 3);

INSERT INTO coaching_services (title, description, icon_name, sort_order) VALUES
('毕业辅导', '针对论文开题、作品集整合及最终答辩的全方位技术性指导。', 'GraduationCap', 1),
('专业实践', '对接意大利当地艺术家工作室，参与真实展览策划与艺术项目。', 'Palette', 2),
('工作室空间', '提供独立创作空间与专业摄影棚，助力高质量作品集的输出与拍摄。', 'Building2', 3);

-- 6. 扩展 site_settings
INSERT INTO site_settings (key, value, description) VALUES
('courses_tag', 'Our Programs', '课程体系页面标签'),
('courses_title', '课程体系', '课程体系页面大标题'),
('courses_description', '我们提供从零基础到专业提升的全方位艺术课程，助您成功升入理想的意大利艺术院校。', '课程体系页面描述'),

('foundation_hero_tag', 'Foundation Programs', '预科课程详情页标签'),
('foundation_hero_title_1', '艺术预科', '预科课程详情页标题1'),
('foundation_hero_title_2', '卓越课程', '预科课程详情页标题2'),
('foundation_hero_description', '现代、极简的艺术留学进修方案。我们为志在顶尖美院的学生提供系统化的作品集指导与艺术史论支撑。', '预科课程详情页描述'),

('coaching_hero_tag', 'ITALIAN FINE ARTS ACADEMY', '辅导课程详情页标签'),
('coaching_hero_title_1', '转学 / 升学 / ', '辅导课程详情页标题1'),
('coaching_hero_title_2', '毕业辅导', '辅导课程详情页标题2'),
('coaching_hero_description', '专为意大利美院在读学生定制的专业进阶指导。我们采用极简画册排版逻辑，助力每一份作品集达到顶级策展水准。', '辅导课程详情页描述'),
('coaching_hero_image', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDj4iAsweewE51ytwfJ_b7bS3v95S1GrOqg3qlESlwu4syHO-txU4fnV0144lu31ZPeMZ-seJFXr8uMr1QEWiTm43m5SwhcuZC45a8ye9vlIqEd7XuAHuotuZlk4aAs0fJ0GwzynDksILpQpYPfzxevXYyu6MvoS_hffkN96Tzi5du4aJ3GJ68FUdTo192mX2w_JF-Z5SYSeTUczxPuDQzxZcnTMqEQ5ByIK3GPhsHjB77Njuf630J8mWScMTox5WNy2IYdAZafhoq9', '辅导课程详情页 Hero 图片'),

('coaching_cta_title_1', '准备好开启你的', '辅导页面 CTA 标题1'),
('coaching_cta_title_2', '艺术进阶', '辅导页面 CTA 标题2'),
('coaching_cta_description', '加入我们，与来自布雷拉、都灵、博洛尼亚等顶尖美院的导师一起，重塑你的艺术语言。', '辅导页面 CTA 描述'),
('coaching_cta_button', '获取免费作品集评估', '辅导页面 CTA 按钮文字')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
