import os
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")

def init_db():
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("未提供 Supabase 环境变量，跳过初始化。")
        return

    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    
    # We will create the contacts table
    # Supabase uses Postgres, so we can execute raw SQL if we have the right permissions
    # However, using the client API to create tables directly isn't officially supported in the standard rested API for Anon Keys
    # We will assume the user has either:
    # 1. Created the table manually
    # 2. Provided a service role key that allows RPC calls to create tables.
    
    print("请确保在 Supabase 的 SQL Editor 中执行以下 SQL 语句来创建表：")
    print('''
    CREATE TABLE IF NOT EXISTS contacts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        phone TEXT NOT NULL,
        message TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
    );
    ''')
    print("数据库初始化提示结束。")

if __name__ == "__main__":
    init_db()
