-- ============================================================
-- ArtAcademy Supabase 数据库初始化脚本
-- 在 Supabase Dashboard 的 SQL Editor 中执行此脚本
-- ============================================================

-- --------------------------------------------------------
-- 1. contacts 表（联系表单提交）
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- --------------------------------------------------------
-- 2. courses 表（课程信息）
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL CHECK (category IN ('standard', 'guarantee')),
    name TEXT NOT NULL,
    tag TEXT,
    duration TEXT NOT NULL,
    format TEXT NOT NULL,
    content TEXT NOT NULL,
    target TEXT NOT NULL,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- --------------------------------------------------------
-- 3. faculty 表（师资团队）
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS faculty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- --------------------------------------------------------
-- 4. cases 表（优秀案例）
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    school TEXT NOT NULL,
    major TEXT NOT NULL,
    image_url TEXT,
    tags TEXT[] DEFAULT '{}',
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- --------------------------------------------------------
-- 5. campuses 表（校区信息）
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS campuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE CHECK (slug IN ('florence', 'milan')),
    name TEXT NOT NULL,
    subtitle TEXT,
    address TEXT NOT NULL,
    description TEXT,
    courses JSONB DEFAULT '[]',
    institutions JSONB DEFAULT '[]',
    gallery_images TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- --------------------------------------------------------
-- 6. testimonials 表（学生反馈）
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_slug TEXT NOT NULL REFERENCES campuses(slug),
    content TEXT NOT NULL,
    student_name TEXT NOT NULL,
    admission_info TEXT,
    avatar_url TEXT,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ============================================================
-- 种子数据
-- ============================================================

-- --------------------------------------------------------
-- courses 种子数据
-- --------------------------------------------------------
INSERT INTO courses (slug, category, name, tag, duration, format, content, target, sort_order) VALUES
('tulanduo-bachelor', 'standard', '"图兰朵"本科预科', NULL, '7个月 / 232课时', '精品小班', '综合艺术创作基础、纯艺技能、入学考前强化', '计划留意高中生', 1),
('tulanduo-master', 'standard', '"图兰朵"研究生预科', NULL, '7个月 / 192课时', '1对1 / 小班', '高级作品集辅导、学术论文指导、策展方案练习', '大四在读/本科毕业生', 2),
('marcopoloh-design', 'standard', '"马可波罗"设计预科', NULL, '7个月 / 222课时', '精品小班', '设计思维建模、软件技能、跨学科设计工作坊', '设计专业申请者', 3),
('art-history', 'standard', '艺术史课程', NULL, '7个月 / 112课时', '精品小班', '艺术史论通识、作品深度分析、考试应答策略', '跨专业及理论薄弱者', 4),
('fomei-guarantee', 'guarantee', '佛美保障预科', 'Premium', '9个月', '全程深度保障', '针对佛罗伦萨美院定向培养、大师讲座、免试直通协议', '目标佛美学生', 1),
('four-academies-guarantee', 'guarantee', '四大美院保障预科', 'Elite', '9个月', '全明星导师团队', '米兰、波美、罗马、都灵美院保录计划、多维度背景提升', '高阶美院冲刺生', 2)
ON CONFLICT (slug) DO NOTHING;

-- --------------------------------------------------------
-- faculty 种子数据
-- --------------------------------------------------------
INSERT INTO faculty (name, title, description, image_url, sort_order) VALUES
('Prof. Giovanni Ferretti', '博洛尼亚美术学院教授 / 罗马艺术史学家', '拥有20年艺术教育经验，专注于意大利文艺复兴艺术史研究。', '/images/teachers/prof-giovanni-ferretti.jpg', 1),
('Prof. Alessandro Ricci', '佛罗伦萨美术学院教授 / 著名雕塑家', '意大利著名雕塑家，作品展出于欧洲多个重要美术馆。', '/images/teachers/prof-alessandro-ricci.jpg', 2),
('Prof. Marco Lombardi', '威尼斯美术学院教授 / 策展人', '资深策展人，曾策划多个威尼斯双年展平行展。', '/images/teachers/prof-marco-lombardi.jpg', 3),
('Prof. Francesca De Angelis', 'NABA新美术学院导师 / 时尚管理', '奢侈品管理专家，曾任职于多家国际时尚集团。', '/images/teachers/prof-francesca-de-angelis.jpg', 4),
('Prof. Luca Moretti', '米兰理工大学教授 / 建筑设计', '专注于可持续建筑设计，参与多个欧洲城市更新项目。', '/images/teachers/prof-luca-moretti.jpg', 5),
('Dr. Elena Conti', '罗马一大博士 / 艺术评论家', '拥有15年艺术评论经验，文章发表于多家国际艺术期刊。', '/images/teachers/dr-elena-conti.jpg', 6),
('Prof. Sofia Benedetti', '欧洲设计学院(IED)教授 / 品牌设计', '品牌设计专家，作品获得多项国际设计大奖。', '/images/teachers/prof-sofia-benedetti.jpg', 7),
('Prof. Andrea Gallo', '马兰欧尼学院教授 / 时尚设计', '资深时尚设计师，曾任职于多家一线奢侈品牌。', '/images/teachers/prof-andrea-gallo.jpg', 8),
('Prof. Chiara Ricci', '都灵美术学院教授 / 装置艺术', '当代装置艺术家，作品展出于威尼斯双年展。', '/images/teachers/prof-chiara-ricci.jpg', 9),
('Prof. Roberto Valenti', '佛路西诺音乐学院教授 / 音乐制作', '资深音乐制作人，拥有丰富的流行音乐制作经验。', '/images/teachers/prof-roberto-valenti.jpg', 10),
('Prof. Antonio Esposito', '佩鲁贾美术学院教授 / 版画与插画', '版画与插画艺术家，作品被多家博物馆收藏。', '/images/teachers/prof-antonio-esposito.jpg', 11),
('Prof. Paola Martinelli', '博洛尼亚音乐学院教授 / 声乐表演', '著名女高音歌唱家，曾在斯卡拉歌剧院演出。', '/images/teachers/prof-paola-martinelli.jpg', 12),
('Prof. Giuseppe Ferrara', '米兰布雷拉美术学院教授 / 绘画与视觉艺术', '当代绘画艺术家，作品展出于欧洲各大美术馆。', '/images/teachers/prof-giuseppe-ferrara.jpg', 13),
('Prof. Maria Teresa Colombo', 'NABA新美术学院导师 / 策展与艺术管理', '艺术管理专家，曾任多个国际艺术展览策展人。', '/images/teachers/prof-maria-teresa-colombo.jpg', 14);

-- --------------------------------------------------------
-- cases 种子数据
-- --------------------------------------------------------
INSERT INTO cases (name, school, major, image_url, tags, sort_order) VALUES
('张同学 (Y. Zhang)', '佛罗伦萨美术学院', '绘画 (Pittura)', 'https://picsum.photos/seed/art1/800/600?blur=2', ARRAY['本科直录', '零基础跨考'], 1),
('李同学 (L. Li)', '米兰理工大学', '室内设计 (Interior Design)', 'https://picsum.photos/seed/art2/800/600?blur=2', ARRAY['研究生录取', '奖学金获得者'], 2),
('王同学 (W. Wang)', '罗马美术学院', '雕塑 (Scultura)', 'https://picsum.photos/seed/art3/800/600?blur=2', ARRAY['图兰朵计划', '高分录取'], 3),
('赵同学 (Z. Zhao)', '马兰欧尼时装学院', '服装设计 (Fashion Design)', 'https://picsum.photos/seed/art4/800/600?blur=2', ARRAY['跨专业申请', '名企实习推荐'], 4),
('陈同学 (C. Chen)', '博洛尼亚美术学院', '插画与漫画 (Fumetto e Illustrazione)', 'https://picsum.photos/seed/art5/800/600?blur=2', ARRAY['本科直录', '独立出版物'], 5),
('刘同学 (L. Liu)', '都灵美术学院', '企业艺术设计 (Progettazione Artistica per l''Impresa)', 'https://picsum.photos/seed/art6/800/600?blur=2', ARRAY['研究生录取', '作品集满分'], 6),
('周同学 (Z. Zhou)', '威尼斯美术学院', '新媒体艺术 (Nuove Tecnologie dell''Arte)', 'https://picsum.photos/seed/art7/800/600?blur=2', ARRAY['马可波罗计划', '科技艺术跨界'], 7),
('吴同学 (W. Wu)', '那不勒斯美术学院', '舞台美术设计 (Scenografia)', 'https://picsum.photos/seed/art8/800/600?blur=2', ARRAY['本科直录', '戏剧节参展'], 8);

-- --------------------------------------------------------
-- campuses 种子数据
-- --------------------------------------------------------
INSERT INTO campuses (slug, name, subtitle, address, description, courses, institutions, gallery_images) VALUES
(
    'florence',
    '佛罗伦萨主校区',
    'Florence Campus',
    'Via San Gallo 10, Firenze, Italy',
    '毗邻百花大教堂，沉浸式感受文艺复兴的艺术气息。佛罗伦萨主校区拥有宽敞明亮的画室、雕塑工坊和艺术史图书馆，为纯艺术方向的学生提供最纯正的意式艺术教育环境。',
    '[
        {"name": "纯艺术 (绘画/雕塑/版画)", "description": "传统技法与当代观念结合，大师级教授亲自指导。"},
        {"name": "舞台美术设计", "description": "结合意大利丰富的歌剧与戏剧资源进行实操。"},
        {"name": "艺术史与策展", "description": "利用佛罗伦萨得天独厚的博物馆资源进行现场教学。"}
    ]'::jsonb,
    '[
        {"name": "佛罗伦萨美术学院", "name_it": "Accademia di Belle Arti di Firenze", "featured": true},
        {"name": "罗马美术学院", "name_it": "Accademia di Belle Arti di Roma", "featured": false},
        {"name": "博洛尼亚美术学院", "name_it": "Accademia di Belle Arti di Bologna", "featured": false},
        {"name": "米兰布雷拉美术学院", "name_it": "Accademia di Belle Arti di Brera", "featured": false}
    ]'::jsonb,
    ARRAY[
        'https://picsum.photos/seed/flor1/600/800',
        'https://picsum.photos/seed/flor2/600/800',
        'https://picsum.photos/seed/flor3/600/800',
        'https://picsum.photos/seed/flor4/600/800'
    ]
),
(
    'milan',
    '米兰校区',
    'Milan Campus',
    'Via Tortona 35, Milano, Italy',
    '位于全球时尚与设计之都的核心区域。米兰校区配备了顶尖的数字媒体实验室、打版工作室和材料库，紧密连接产业前沿，专注于设计与时尚类专业辅导。',
    '[
        {"name": "服装与时尚设计", "description": "从概念版型到成衣制作，对接一线奢侈品牌标准。"},
        {"name": "室内与空间设计", "description": "涵盖商业空间、住宅及展览展示设计，强化软件技能。"},
        {"name": "产品与交互设计", "description": "聚焦用户体验与可持续设计，配备3D打印等原型制作设备。"}
    ]'::jsonb,
    '[
        {"name": "米兰理工大学", "name_it": "Politecnico di Milano", "featured": true},
        {"name": "马兰欧尼时装学院", "name_it": "Istituto Marangoni", "featured": false},
        {"name": "NABA 新美术学院", "name_it": "Nuova Accademia di Belle Arti", "featured": false}
    ]'::jsonb,
    ARRAY[
        'https://picsum.photos/seed/milan1/600/800',
        'https://picsum.photos/seed/milan2/600/800',
        'https://picsum.photos/seed/milan3/600/800',
        'https://picsum.photos/seed/milan4/600/800'
    ]
)
ON CONFLICT (slug) DO NOTHING;

-- --------------------------------------------------------
-- testimonials 种子数据
-- --------------------------------------------------------
INSERT INTO testimonials (campus_slug, content, student_name, admission_info, avatar_url, sort_order) VALUES
-- 佛罗伦萨校区反馈
('florence', '在佛罗伦萨校区学习的这半年是我人生中最宝贵的经历。每天走过乌菲兹美术馆去上课，教授们不仅教技法，更教我们如何像真正的艺术家一样思考。', '李同学', '录取至 佛罗伦萨美术学院', 'https://picsum.photos/seed/user1/100/100', 1),
('florence', '画室的采光特别好，氛围很浓厚。这里的模拟面试帮了我大忙，真正面对考官时我一点都不紧张了。', '张同学', '录取至 罗马美术学院', 'https://picsum.photos/seed/user2/100/100', 2),
('florence', '老师们非常负责，我的作品集排版改了无数次，最终呈现的效果连我自己都惊艳到了。强烈推荐这里的保障课程！', '王同学', '录取至 博洛尼亚美术学院', 'https://picsum.photos/seed/user3/100/100', 3),
-- 米兰校区反馈
('milan', '米兰校区的设备太全了！我的交互设计作品集需要很多硬件原型的展示，这里的实验室完全满足了我的需求。', '赵同学', '录取至 米兰理工大学', 'https://picsum.photos/seed/user4/100/100', 1),
('milan', '导师本身就是马兰欧尼的客座教授，对作品集的风格把控极其精准。在她的指导下，我成功拿到了高额奖学金。', '刘同学', '录取至 马兰欧尼时装学院', 'https://picsum.photos/seed/user5/100/100', 2),
('milan', '在米兰设计周期间，学校还组织我们去看了很多展，极大地拓宽了我的设计视野。这里的资源是无价的。', '陈同学', '录取至 NABA 新美术学院', 'https://picsum.photos/seed/user6/100/100', 3);

-- ============================================================
-- RLS 策略（如果使用 anon/publishable key）
-- NOTE: 按需启用，如果使用 service_role key 可跳过
-- ============================================================

-- 允许匿名用户读取公开数据
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许匿名读取课程" ON courses FOR SELECT USING (true);

ALTER TABLE faculty ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许匿名读取师资" ON faculty FOR SELECT USING (true);

ALTER TABLE cases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许匿名读取案例" ON cases FOR SELECT USING (true);

ALTER TABLE campuses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许匿名读取校区" ON campuses FOR SELECT USING (true);

ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许匿名读取反馈" ON testimonials FOR SELECT USING (true);

-- 允许匿名用户提交联系表单
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许匿名提交联系表单" ON contacts FOR INSERT WITH CHECK (true);
CREATE POLICY "禁止匿名读取联系表单" ON contacts FOR SELECT USING (false);
